# PowerShell script to send development questions to core.core --planOnly and log Q/A pairs
chcp 65001
$OutputEncoding = [System.Text.Encoding]::UTF8

$questions = @(
    "Summarize what this function/class/file does.",
    "Explain this error message and how to fix it.",
    "Refactor this code for readability/performance.",
    "Write unit tests for this function.",
    "Suggest edge cases for this logic.",
    "Generate a docstring for this function.",
    "Convert this code from Python to JavaScript (or another language).",
    "What libraries can help with X task?",
    "How do I use [library/class/function]?",
    "Find bugs or potential issues in this code.",
    "Suggest a regular expression for this pattern.",
    "What is the time/space complexity of this function?",
    "How can I optimize this loop/algorithm?",
    "What are best practices for [framework/language]?",
    "Generate a SQL query for this data need.",
    "How do I mock this dependency in tests?",
    "What’s the difference between X and Y in this context?",
    "How do I set up CI/CD for this project?",
    "What’s a good commit message for these changes?",
    "How do I fix this merge conflict?"
)

$questions += @(
    "How do I debug a failing test?",
    "What is the purpose of this decorator?",
    "How do I handle exceptions in this code?",
    "What are common security risks in this code?",
    "How do I write a migration for this database schema?",
    "How do I profile memory usage in this script?",
    "What is the difference between synchronous and asynchronous code?",
    "How do I implement caching for this function?",
    "How do I use environment variables in this project?",
    "How do I set up logging for this application?",
    "How do I validate user input in this form?",
    "How do I create a REST API endpoint?",
    "How do I use dependency injection here?",
    "How do I write a Dockerfile for this project?",
    "How do I deploy this app to AWS/GCP/Azure?",
    "How do I use git rebase safely?",
    "How do I resolve circular imports?",
    "How do I use type hints in Python?",
    "How do I optimize SQL queries in this code?",
    "How do I use pytest fixtures?",
    "How do I mock HTTP requests in tests?",
    "How do I implement pagination in this API?",
    "How do I use context managers in Python?",
    "How do I write a custom exception?",
    "How do I use regular expressions for validation?",
    "How do I handle time zones in this app?",
    "How do I use async/await in Python?",
    "How do I write a CLI tool for this script?",
    "How do I use the requests library?",
    "How do I serialize data to JSON?",
    "How do I deserialize JSON to objects?",
    "How do I use list comprehensions?",
    "How do I use generators for large datasets?",
    "How do I implement a singleton pattern?",
    "How do I use the observer pattern?",
    "How do I use the factory pattern?",
    "How do I use the strategy pattern?",
    "How do I use the command pattern?",
    "How do I use the adapter pattern?",
    "How do I use the proxy pattern?",
    "How do I use the facade pattern?",
    "How do I use the builder pattern?",
    "How do I use the composite pattern?",
    "How do I use the decorator pattern?",
    "How do I use the MVC pattern?",
    "How do I use the MVVM pattern?",
    "How do I use the MVP pattern?",
    "How do I use the repository pattern?",
    "How do I use the service pattern?",
    "How do I use the DAO pattern?",
    "How do I use the DTO pattern?",
    "How do I use the active record pattern?",
    "How do I use the data mapper pattern?",
    "How do I use the lazy loading pattern?",
    "How do I use the template method pattern?",
    "How do I use the state pattern?",
    "How do I use the chain of responsibility pattern?",
    "How do I use the mediator pattern?",
    "How do I use the interpreter pattern?",
    "How do I use the visitor pattern?",
    "How do I use the flyweight pattern?",
    "How do I use the bridge pattern?",
    "How do I use the prototype pattern?",
    "How do I use the command line arguments in Python?",
    "How do I use the argparse library?",
    "How do I use the click library?",
    "How do I use the rich library for output?",
    "How do I use the logging library?",
    "How do I use the unittest library?",
    "How do I use the mock library?",
    "How do I use the patch decorator?",
    "How do I use the MagicMock class?",
    "How do I use the PropertyMock class?",
    "How do I use the side_effect argument?",
    "How do I use the autospec argument?",
    "How do I use the pytest.mark.parametrize decorator?",
    "How do I use the pytest.raises context manager?",
    "How do I use the pytest.skip function?",
    "How do I use the pytest.xfail function?",
    "How do I use the pytest.fixture decorator?",
    "How do I use the pytest-mock plugin?",
    "How do I use the pytest-cov plugin?",
    "How do I use the pytest-django plugin?",
    "How do I use the pytest-flask plugin?",
    "How do I use the pytest-asyncio plugin?",
    "How do I use the pytest-benchmark plugin?",
    "How do I use the pytest-sugar plugin?",
    "How do I use the pytest-html plugin?",
    "How do I use the pytest-xdist plugin?",
    "How do I use the pytest-randomly plugin?",
    "How do I use the pytest-ordering plugin?",
    "How do I use the pytest-forked plugin?",
    "How do I use the pytest-timeout plugin?",
    "How do I use the pytest-repeat plugin?",
    "How do I use the pytest-subtests plugin?",
    "How do I use the pytest-metadata plugin?",
    "How do I use the pytest-dependency plugin?",
    "How do I use the pytest-lazy-fixture plugin?",
    "How do I use the pytest-recording plugin?",
    "How do I use the pytest-socket plugin?",
    "How do I use the pytest-mockserver plugin?",
    "How do I use the pytest-localserver plugin?",
    "How do I use the pytest-httpserver plugin?",
    "How do I use the pytest-requests plugin?",
    "How do I use the pytest-vcr plugin?",
    "How do I use the pytest-freezegun plugin?",
    "How do I use the pytest-datadir plugin?",
    "How do I use the pytest-datadir-ng plugin?",
    "How do I use the pytest-datadir-factory plugin?",
    "How do I use the pytest-datadir-mock plugin?",
    "How do I use the pytest-datadir-utils plugin?"
)

$logFile = "llm_planOnly_log.txt"
Remove-Item $logFile -ErrorAction SilentlyContinue

foreach ($q in $questions) {
    Add-Content $logFile "QUESTION: $q"
    $answer = python -m core.core --planOnly "$q" 2>&1
    Add-Content $logFile "ANSWER:`n$answer`n`n-----------------------------`n"
}

Write-Host "All questions processed. See $logFile for results."
